/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : DC_DIR_SET.c
**     Project     : NIOday_Stop
**     Processor   : MKE06Z128VLD4
**     Component   : BitsIO
**     Version     : Component 02.108, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-11-07, 21:02, # CodeGen: 1
**     Abstract    :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings    :
**          Component name                                 : DC_DIR_SET
**          Port                                           : GPIOA
**          BitsIO_LDD                                     : BitsIO_LDD
**          Pins                                           : 2
**            Pin0                                         : 
**              Pin                                        : PTB2/KBI0_P10/SPI0_SCK/FTM0_CH0/ADC0_SE6
**            Pin1                                         : 
**              Pin                                        : PTB3/KBI0_P11/SPI0_MOSI/FTM0_CH1/ADC0_SE7
**          Direction                                      : Output
**          Initialization                                 : 
**            Init. direction                              : Output
**            Init. value                                  : 0
**          Safe mode                                      : yes
**          Optimization for                               : speed
**     Contents    :
**         GetDir - bool DC_DIR_SET_GetDir(void);
**         GetVal - byte DC_DIR_SET_GetVal(void);
**         PutVal - void DC_DIR_SET_PutVal(byte Val);
**         GetBit - bool DC_DIR_SET_GetBit(byte Bit);
**         PutBit - void DC_DIR_SET_PutBit(byte Bit, bool Val);
**         SetBit - void DC_DIR_SET_SetBit(byte Bit);
**         ClrBit - void DC_DIR_SET_ClrBit(byte Bit);
**         NegBit - void DC_DIR_SET_NegBit(byte Bit);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file DC_DIR_SET.c
** @version 01.00
** @brief
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
*/         
/*!
**  @addtogroup DC_DIR_SET_module DC_DIR_SET module documentation
**  @{
*/         

/* MODULE DC_DIR_SET. */

#include "DC_DIR_SET.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*
** ===================================================================
**     Method      :  DC_DIR_SET_GetDir (component BitsIO)
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always <true>, Output only)
**                      <false> = Input, <true> = Output
** ===================================================================
*/
/*
bool DC_DIR_SET_GetDir(void)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/*
** ===================================================================
**     Method      :  DC_DIR_SET_GetVal (component BitsIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 3)
** ===================================================================
*/
/*
byte DC_DIR_SET_GetVal(void)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/*
** ===================================================================
**     Method      :  DC_DIR_SET_PutVal (component BitsIO)
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
/*
void DC_DIR_SET_PutVal(byte Val)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/*
** ===================================================================
**     Method      :  DC_DIR_SET_GetBit (component BitsIO)
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 1)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool DC_DIR_SET_GetBit(byte Bit)
{
  bool BitVal;

  (void)BitsIoLdd1_GetBit(BitsIoLdd1_DeviceData, Bit, &BitVal);
  return (BitVal);
}

/*
** ===================================================================
**     Method      :  DC_DIR_SET_PutBit (component BitsIO)
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 1)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
/*
void DC_DIR_SET_PutBit(byte Bit, bool Val)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/*
** ===================================================================
**     Method      :  DC_DIR_SET_SetBit (component BitsIO)
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
/*
void DC_DIR_SET_SetBit(byte Bit)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/*
** ===================================================================
**     Method      :  DC_DIR_SET_ClrBit (component BitsIO)
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 1)
**     Returns     : Nothing
** ===================================================================
*/
/*
void DC_DIR_SET_ClrBit(byte Bit)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/*
** ===================================================================
**     Method      :  DC_DIR_SET_NegBit (component BitsIO)
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
/*
void DC_DIR_SET_NegBit(byte Bit)

**  This method is implemented as a macro. See DC_DIR_SET.h file.  **
*/

/* END DC_DIR_SET. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
